/**
 * seedAgents.ts
 *
 * Seeds 2 agents onto localnet/devnet:
 *   - Agent A → Bronze (score: 35)
 *   - Agent B → Gold   (score: 92)
 *
 * Usage: npx ts-node scripts/seedAgents.ts
 */

import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
  Keypair,
  PublicKey,
  SystemProgram,
  Connection,
  clusterApiUrl,
} from "@solana/web3.js";
import * as fs from "fs";
import * as path from "path";

// Load IDL (generated by `anchor build`)
const IDL_PATH = path.resolve(__dirname, "../target/idl/trustgate.json");

async function main() {
  // Setup provider
  const connection = new Connection("http://localhost:8899", "confirmed");

  // Load wallet from default Solana keygen path
  const walletPath =
    process.env.ANCHOR_WALLET ||
    `${process.env.HOME || process.env.USERPROFILE}/.config/solana/id.json`;
  const secretKey = JSON.parse(fs.readFileSync(walletPath, "utf-8"));
  const authority = Keypair.fromSecretKey(Uint8Array.from(secretKey));

  const wallet = new anchor.Wallet(authority);
  const provider = new anchor.AnchorProvider(connection, wallet, {
    commitment: "confirmed",
  });
  anchor.setProvider(provider);

  // Load IDL
  let idl: anchor.Idl;
  try {
    idl = JSON.parse(fs.readFileSync(IDL_PATH, "utf-8"));
  } catch {
    console.error("❌ IDL not found. Run `anchor build` first.");
    process.exit(1);
  }

  const programId = new PublicKey(idl.address || "TRSTgateXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
  const program = new Program(idl, programId, provider);

  console.log("🔑 Authority:", authority.publicKey.toBase58());
  console.log("📡 Cluster:", connection.rpcEndpoint);
  console.log("📦 Program:", programId.toBase58());
  console.log("");

  // ---- Agent A: Bronze ----
  const agentA = Keypair.generate();
  const [passportA] = PublicKey.findProgramAddressSync(
    [Buffer.from("passport"), agentA.publicKey.toBuffer()],
    programId
  );

  console.log("🤖 Agent A (Bronze):", agentA.publicKey.toBase58());
  try {
    await program.methods
      .initializePassport(35)
      .accounts({
        passport: passportA,
        agent: agentA.publicKey,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();
    console.log("   ✅ Passport created — Score: 35, Tier: Bronze");
  } catch (err: any) {
    console.log("   ❌ Error:", err.message);
  }

  // ---- Agent B: Gold ----
  const agentB = Keypair.generate();
  const [passportB] = PublicKey.findProgramAddressSync(
    [Buffer.from("passport"), agentB.publicKey.toBuffer()],
    programId
  );

  console.log("🤖 Agent B (Gold):", agentB.publicKey.toBase58());
  try {
    await program.methods
      .initializePassport(92)
      .accounts({
        passport: passportB,
        agent: agentB.publicKey,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();
    console.log("   ✅ Passport created — Score: 92, Tier: Gold");
  } catch (err: any) {
    console.log("   ❌ Error:", err.message);
  }

  console.log("");
  console.log("🎉 Seeding complete!");
  console.log("");
  console.log("Agents seeded:");
  console.log(`  Agent A (Bronze): ${agentA.publicKey.toBase58()}`);
  console.log(`  Agent B (Gold):   ${agentB.publicKey.toBase58()}`);

  // Save keys for simulation script
  const seedData = {
    agentA: {
      publicKey: agentA.publicKey.toBase58(),
      secretKey: Array.from(agentA.secretKey),
      tier: "Bronze",
      score: 35,
    },
    agentB: {
      publicKey: agentB.publicKey.toBase58(),
      secretKey: Array.from(agentB.secretKey),
      tier: "Gold",
      score: 92,
    },
  };

  const outputPath = path.resolve(__dirname, "seeded-agents.json");
  fs.writeFileSync(outputPath, JSON.stringify(seedData, null, 2));
  console.log(`\n📝 Agent keys saved to ${outputPath}`);
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
